name: .NET Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: STD_Database   # 👈 Ensures all commands run inside this folder

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore STD_Database.csproj

    - name: Build project
      run: dotnet build STD_Database.csproj --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-build --verbosity normal